import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  IconActivity,
  IconAlertCircle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconCalendar,
  IconCheckCircle,
  IconDelete,
  IconDroplet,
  IconEdit3,
  IconFacebook,
  IconFeather,
  IconFolder,
  IconHeart,
  IconHome,
  IconInfo,
  IconLink,
  IconList,
  IconMap,
  IconMapPin,
  IconMenu,
  IconMessageCircle,
  IconMoreHorizontal,
  IconNavigation2,
  IconPlus,
  IconSave,
  IconSearch,
  IconShoppingCart,
  IconSliders,
  IconSmartphone,
  IconStar,
  IconTag,
  IconThumbsDown,
  IconThumbsUp,
  IconUpload,
  IconUploadCloud,
  IconUser,
  IconX
} from 'angular-feather';
import { IconMinus } from 'angular-feather';

@NgModule({
  imports: [CommonModule],
  declarations: [],
  exports: [
    IconActivity,
    IconHome,
    IconArrowDown,
    IconArrowLeft,
    IconArrowRight,
    IconAlertCircle,
    IconCheckCircle,
    IconDelete,
    IconEdit3,
    IconFacebook,
    IconMessageCircle,
    IconSave,
    IconSearch,
    IconShoppingCart,
    IconSmartphone,
    IconTag,
    IconSliders,
    IconUser,
    IconList,
    IconStar,
    IconThumbsUp,
    IconThumbsDown,
    IconUploadCloud,
    IconUpload,
    IconX,
    IconPlus,
    IconMinus,
    IconMenu,
    IconMapPin,
    IconMap,
    IconLink,
    IconHeart,
    IconInfo,
    IconFolder,
    IconCalendar,
    IconNavigation2,
    IconMoreHorizontal,
    IconDroplet,
    IconFeather
  ]
})
export class IconsModule {}
